DEFAULT_CONFIG = {
    "world": {"width": 2000, "height": 2000, "background": 18},
    "camera": {
        "resolution": [640, 480],
        "fov_deg": [4.0, 3.0],
        "fps": 30.0,
        "max_pan_speed": 5.0,
        "max_tilt_speed": 5.0,
        "jitter_px": 0.0,
    },
    "target": {
        "size": 10,
        "intensity": 255,
        "trajectory": "circular",
        "speed_px_per_frame": 2.8,
        "initial_pos": [1000, 900],  # near center for reliable demo; set to None for random benchmark
        "angle_deg": 30.0,
        "radius": 180.0,
    },
    "platform": {"type": "linear", "speed_px_per_frame": 0.0, "amplitude": 0.0},
    "noise": {
        "gaussian_std": 0.0,
        "salt_pepper_prob": 0.0,
        "poisson": False,
        "gaussian_enabled": False,
        "salt_pepper_enabled": False,
    },
    "atmosphere": {"type": "clear", "strength": 0.0},
    "detector": {
        "threshold_k": 3.0,
        "min_area": 8,
        "max_area": 900,
        "blur_ksize": 3,
        "adaptive_block": 51,
        "adaptive_C": -5,
    },
    "tracker": {
        "process_noise": 0.8,
        "meas_noise": 4.0,
        "gate_sigma": 5.0,
        "lost_timeout_frames": 15,
        "reacq_timeout_frames": 30,
    },
    "controller": {
        "kp_pan": 1.2,
        "kp_tilt": 1.2,
        "ki": 0.05,
        "kd": 0.15,
        "deadzone_px": 2.0,
        "integral_limit": 8.0,
        "feedforward_gain": 0.0,
    },
    "experiment": {"duration_s": 30.0, "seed": 42, "input_mode": "SYNTHETIC", "video_path": ""},
}
